import Head from "next/head";
import { useRouter } from "next/router";
import Button from "../components/Button/Button";
import styles from "../styles/login.module.css";

import { useMoralis } from "react-moralis";
import { useEffect } from "react";

export default function Home() {
  const { authenticate, isAuthenticated, user, auth } = useMoralis();
  const router = useRouter();

  const login = async (authMethod) => {
    try {
      if (authMethod == "metamask") {
        await authenticate({ signingMessage: "Welcome to Flipkart Grid" });
      } else if (authMethod == "walletconnect") {
        await authenticate({
          provider: "walletconnect",
          mobileLinks: [
            "rainbow",
            "metamask",
            "argent",
            "trust",
            "imtoken",
            "pillar",
          ],
          signingMessage: "Welcome to Flipkart Grid",
        });
      }
      router.push("/bulkupload");
    } catch (err) {
      console.error(err);
    }
  };

  // useEffect(() => {
  //   if (isAuthenticated) {
  //     router.push("/bulkupload");
  //   }
  // }, [isAuthenticated]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.login}>
        <div className={styles.login__left}>
          <div>
            We&apos;ve been developing the next standard of reusable cell phones
          </div>
          <div className={styles.info}>
            <h4>Apple Inc.</h4>
            <p>NFT Warranty and minting platform</p>
            <p>Next era of digital warranty cards</p>
          </div>
        </div>
        <div className={styles.login__right}>
          <h2>Login to account</h2>
          <p>Only the owners of the blockchain can access this platform</p>
          <div className={styles.buttons}>
            <Button text={"METAMASK"} click={() => login("metamask")} />
            <Button
              text={"WALLETCONNECT"}
              click={() => login("walletconnect")}
            />
          </div>
          <p>Only the owners of the blockchain can access this platform</p>
        </div>
      </main>
    </div>
  );
}
